//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios de este archivo pueden provocar un comportamiento inesperado y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCR.UDSystem.Interfaz.CU_EstadisticasUso
{


    public partial class ConsultaEstadistica
    {
    }
}
